In [ ]:
#cd Downloads\Capstone

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dataSet = pd.read_csv('/content/drive/MyDrive/Data/Diabetestype.csv')
dataSet

      Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c    Type  Class
0      50      6.8    8.8      11.2       7.2     62   Type1      1
1      31      5.2    6.8      10.9       4.2     33  Normal      0
2      32      6.8    8.8      11.2       7.2     62   Type1      1
3      21      5.7    5.8      10.7       4.8     49  Normal      0
4      33      6.8    8.8      11.2       7.2     62   Type1      1
...   ...      ...    ...       ...       ...    ...     ...    ...
1004   37      0.0    5.6      10.2       5.4     32  Normal      0
1005   23      6.3    4.2      12.2       7.8     57   Type2      1
1006   37     32.0    7.4       8.7       5.6     41  Normal      0
1007   46     19.0    6.3       7.9       3.9     40  Normal      0
1008   25     16.0    6.3       7.9       3.9     40  Normal      0

[1009 rows x 8 columns]

In [ ]:
diabetes_true_count = len(dataSet.loc[dataSet['Class'] == True])
diabetes_false_count = len(dataSet.loc[dataSet['Class'] == False])

print("True Outcome: {0}, False Outcome: {1}".format(diabetes_true_count, diabetes_false_count))

True Outcome: 378, False Outcome: 631

In [ ]:
Outcome=[]
for i in dataSet.Type:
    if i=='Normal':
        Outcome.append(0)
    elif i=='Type1':
        Outcome.append(1)
    elif i=='Type2':
        Outcome.append(2)

In [ ]:
len(Outcome)

1009

In [ ]:
dataSet['Outcomes']=Outcome # setting the outcome column

In [ ]:
dataSet=dataSet.drop('Class',axis=1)
dataSet=dataSet.drop('Type',axis=1)
dataSet

      Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c  Outcomes
0      50      6.8    8.8      11.2       7.2     62         1
1      31      5.2    6.8      10.9       4.2     33         0
2      32      6.8    8.8      11.2       7.2     62         1
3      21      5.7    5.8      10.7       4.8     49         0
4      33      6.8    8.8      11.2       7.2     62         1
...   ...      ...    ...       ...       ...    ...       ...
1004   37      0.0    5.6      10.2       5.4     32         0
1005   23      6.3    4.2      12.2       7.8     57         2
1006   37     32.0    7.4       8.7       5.6     41         0
1007   46     19.0    6.3       7.9       3.9     40         0
1008   25     16.0    6.3       7.9       3.9     40         0

[1009 rows x 7 columns]

In [ ]:
diabetes_Normal_count = len(dataSet.loc[dataSet['Outcomes'] == 0])
diabetes_Type1_count = len(dataSet.loc[dataSet['Outcomes'] == 1])
diabetes_Type2_count = len(dataSet.loc[dataSet['Outcomes'] == 2])

print("Normal Outcome: {0}, Type1 Outcome: {1}, Type2 Outcome: {2}".format(diabetes_Normal_count, diabetes_Type1_count, diabetes_Type2_count))

Normal Outcome: 631, Type1 Outcome: 173, Type2 Outcome: 205

In [ ]:
dataSet.rename({'BS Fast':'BS_Fast','BS pp':'BS_pp','Plasma R':'Plasma_R','Plasma F':'Plasma_F'},axis = 1, inplace = True)

In [ ]:
upper_list=[]
lower_list=[]

age_mean=dataSet.Age.mean()
age_std=dataSet.Age.std()
upper_list.append(age_mean+(age_std*3))
lower_list.append(age_mean-(age_std*3))
print('Age_mean:',age_mean,end=" ")
print('Age_std:',age_std)
bs_Fast_mean=dataSet.BS_Fast.mean()
bs_Fast_std=dataSet.BS_Fast.std()
upper_list.append(bs_Fast_mean+(bs_Fast_std*3))
lower_list.append(bs_Fast_mean-(bs_Fast_std*3))
print('bs_Fast_mean:',bs_Fast_mean,end=" ")
print('bs_Fast_std:',bs_Fast_std)
bs_pp_mean=dataSet.BS_pp.mean()
bs_pp_std=dataSet.BS_pp.std()
upper_list.append(bs_pp_mean+(bs_pp_std*3))
lower_list.append(bs_pp_mean-(bs_pp_std*3))
print('bs_pp_mean:',bs_pp_mean,end=" ")
print('bs_pp_std:',bs_pp_std)
plasma_R_mean=dataSet.Plasma_R.mean()
plasma_R_std=dataSet.Plasma_R.std()
upper_list.append(plasma_R_mean+(plasma_R_std*3))
lower_list.append(plasma_R_mean-(plasma_R_std*3))
print('plasma_R_mean:',plasma_R_mean,end=" ")
print('plasma_R_std:',plasma_R_std)
plasma_F_mean=dataSet.Plasma_F.mean()
plasma_F_std=dataSet.Plasma_F.std()
upper_list.append(plasma_F_mean+(plasma_F_std*3))
lower_list.append(plasma_F_mean-(plasma_F_std*3))
print('plasma_F_mean:',plasma_F_mean,end=" ")
print('plasma_F_std:',plasma_F_std)
hba1c_mean=dataSet.HbA1c.mean()
hba1c_std=dataSet.HbA1c.std()
print('hba1c_mean:',hba1c_mean,end=" ")
print('hba1c_std:',hba1c_std)
lower_list.append(hba1c_mean-(hba1c_std*3))
upper_list.append(hba1c_mean+(hba1c_std*3))


print('List=',upper_list)
print('List=',lower_list)

Age_mean: 33.39841427155599 Age_std: 11.633363925070421
bs_Fast_mean: 12.571853320118922 bs_Fast_std: 12.334018667987877
bs_pp_mean: 6.659167492566903 bs_pp_std: 1.205187901396455
plasma_R_mean: 10.728741328047592 plasma_R_std: 1.436978511856844
plasma_F_mean: 6.136075322101089 plasma_F_std: 1.6206586875781563
hba1c_mean: 43.4816650148662 hba1c_std: 12.06751471972127
List= [68.29850604676726, 49.57390932408255, 10.274731196756267, 15.039676863618125, 10.998051384835557, 79.68420917403]
List= [-1.501677503655273, -24.43020268384471, 3.0436037883775375, 6.4178057924770595, 1.2740992593666203, 7.279120855702395]

age_mean=dataSet.Age.mean()
age_std=dataSet.Age.std()
print(age_mean)
print(age_std)

In [ ]:
dataSet

      Age  BS_Fast  BS_pp  Plasma_R  Plasma_F  HbA1c  Outcomes
0      50      6.8    8.8      11.2       7.2     62         1
1      31      5.2    6.8      10.9       4.2     33         0
2      32      6.8    8.8      11.2       7.2     62         1
3      21      5.7    5.8      10.7       4.8     49         0
4      33      6.8    8.8      11.2       7.2     62         1
...   ...      ...    ...       ...       ...    ...       ...
1004   37      0.0    5.6      10.2       5.4     32         0
1005   23      6.3    4.2      12.2       7.8     57         2
1006   37     32.0    7.4       8.7       5.6     41         0
1007   46     19.0    6.3       7.9       3.9     40         0
1008   25     16.0    6.3       7.9       3.9     40         0

[1009 rows x 7 columns]

In [ ]:
len(upper_list)

6

In [ ]:
diabetes_Normal_count

631

In [ ]:
count=0
for i in dataSet.Outcomes:
    if i==0 and count<600:#array index error khai
        flag0=(dataSet.iloc[count,0]<upper_list[0] and dataSet.iloc[count,0]>lower_list[0])
        flag1=(dataSet.iloc[count,1]<upper_list[1] and dataSet.iloc[count,1]>lower_list[1])
        flag2=(dataSet.iloc[count,2]<upper_list[2] and dataSet.iloc[count,2]>lower_list[2])
        flag3=(dataSet.iloc[count,3]<upper_list[3] and dataSet.iloc[count,3]>lower_list[3])
        flag4=(dataSet.iloc[count,4]<upper_list[4] and dataSet.iloc[count,4]>lower_list[4])
        flag5=(dataSet.iloc[count,5]<upper_list[5] and dataSet.iloc[count,5]>lower_list[5])
        #print(flag0," ",flag1," ",flag2," ",flag3," ",flag4," ",flag5," ",)
        if(flag0 or flag1 or flag2 or flag3 or flag4 or flag5):
            print(dataSet.iloc[count,:])
            dataSet=dataSet.drop(count)
            #print(count)
            count+=1
    else:
        #print(count)
        count+=1

Age         31.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 1, dtype: float64
Age         33.0
BS_Fast      6.8
BS_pp        8.8
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     1.0
Name: 4, dtype: float64
Age         29.0
BS_Fast      5.2
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 7, dtype: float64
Age         30.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 10, dtype: float64
Age         51.0
BS_Fast      6.8
BS_pp        8.2
Plasma_R    11.6
Plasma_F     7.4
HbA1c       69.0
Outcomes     2.0
Name: 14, dtype: float64
Age         31.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 17, dtype: float64
Age         51.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 24, dtype: float64
Age         22.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 27, dtype: float64
Age         38.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 29, dtype: float64
Age         35.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 36, dtype: float64
Age         27.0
BS_Fast      6.7
BS_pp        7.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     1.0
Name: 38, dtype: float64
Age         26.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 40, dtype: float64
Age         48.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 42, dtype: float64
Age         25.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     1.0
Name: 45, dtype: float64
Age         22.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 47, dtype: float64
Age         24.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 49, dtype: float64
Age         26.0
BS_Fast      4.8
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 51, dtype: float64
Age         58.0
BS_Fast      6.7
BS_pp        7.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     1.0
Name: 53, dtype: float64
Age         44.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 58, dtype: float64
Age         21.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 60, dtype: float64
Age         36.0
BS_Fast      5.2
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 62, dtype: float64
Age         32.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 65, dtype: float64
Age         25.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 68, dtype: float64
Age         28.0
BS_Fast      5.8
BS_pp        6.3
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     1.0
Name: 70, dtype: float64
Age         23.0
BS_Fast      4.8
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 73, dtype: float64
Age         22.0
BS_Fast      5.2
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 75, dtype: float64
Age         27.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 77, dtype: float64
Age         24.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 79, dtype: float64
Age         36.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 82, dtype: float64
Age         37.0
BS_Fast      5.8
BS_pp        6.3
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     1.0
Name: 84, dtype: float64
Age         26.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 87, dtype: float64
Age         24.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 89, dtype: float64
Age         34.0
BS_Fast      5.2
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 91, dtype: float64
Age         60.0
BS_Fast      6.7
BS_pp        8.7
Plasma_R    11.6
Plasma_F     7.4
HbA1c       69.0
Outcomes     1.0
Name: 93, dtype: float64
Age         24.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 96, dtype: float64
Age         23.0
BS_Fast      5.7
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 98, dtype: float64
Age         22.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 101, dtype: float64
Age         27.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 104, dtype: float64
Age         27.0
BS_Fast      4.8
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 106, dtype: float64
Age         25.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 108, dtype: float64
Age         46.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     1.0
Name: 111, dtype: float64
Age         39.0
BS_Fast      6.8
BS_pp        8.8
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     1.0
Name: 114, dtype: float64
Age         38.0
BS_Fast      6.8
BS_pp        8.8
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     1.0
Name: 116, dtype: float64
Age         22.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 118, dtype: float64
Age         25.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     1.0
Name: 120, dtype: float64
Age         23.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 122, dtype: float64
Age         26.0
BS_Fast      5.8
BS_pp        6.3
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     1.0
Name: 125, dtype: float64
Age         23.0
BS_Fast      5.2
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 127, dtype: float64
Age         62.0
BS_Fast      6.8
BS_pp        8.2
Plasma_R    11.6
Plasma_F     7.4
HbA1c       69.0
Outcomes     2.0
Name: 129, dtype: float64
Age         33.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     1.0
Name: 131, dtype: float64
Age         39.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 133, dtype: float64
Age         21.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 136, dtype: float64
Age         29.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 138, dtype: float64
Age         55.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 140, dtype: float64
Age         42.0
BS_Fast      5.8
BS_pp        4.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     2.0
Name: 143, dtype: float64
Age         50.0
BS_Fast      6.8
BS_pp        4.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     2.0
Name: 145, dtype: float64
Age         42.0
BS_Fast      5.2
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 147, dtype: float64
Age         21.0
BS_Fast      5.2
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 149, dtype: float64
Age         22.0
BS_Fast      5.2
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 152, dtype: float64
Age         31.0
BS_Fast      6.8
BS_pp        8.8
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     1.0
Name: 154, dtype: float64
Age         22.0
BS_Fast      5.2
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 156, dtype: float64
Age         42.0
BS_Fast     20.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     7.2
HbA1c       36.0
Outcomes     0.0
Name: 158, dtype: float64
Age         21.0
BS_Fast      0.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 160, dtype: float64
Age         21.0
BS_Fast     16.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 164, dtype: float64
Age         22.0
BS_Fast     25.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 166, dtype: float64
Age         29.0
BS_Fast      0.0
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 168, dtype: float64
Age         36.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     1.0
Name: 170, dtype: float64
Age         25.0
BS_Fast     23.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 172, dtype: float64
Age         33.0
BS_Fast     24.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 174, dtype: float64
Age         42.0
BS_Fast      0.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 176, dtype: float64
Age         47.0
BS_Fast      0.0
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 178, dtype: float64
Age         27.0
BS_Fast      0.0
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 183, dtype: float64
Age         41.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 185, dtype: float64
Age         21.0
BS_Fast      0.0
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 190, dtype: float64
Age         36.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     1.0
Name: 192, dtype: float64
Age         42.0
BS_Fast     20.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     7.2
HbA1c       36.0
Outcomes     0.0
Name: 194, dtype: float64
Age         23.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     1.0
Name: 197, dtype: float64
Age         29.0
BS_Fast      6.7
BS_pp        7.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     1.0
Name: 199, dtype: float64
Age         28.0
BS_Fast      0.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 201, dtype: float64
Age         27.0
BS_Fast     28.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 205, dtype: float64
Age         52.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     1.0
Name: 207, dtype: float64
Age         36.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     1.0
Name: 214, dtype: float64
Age         25.0
BS_Fast      6.1
BS_pp        5.7
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     2.0
Name: 216, dtype: float64
Age         32.0
BS_Fast      6.3
BS_pp        4.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     2.0
Name: 218, dtype: float64
Age         21.0
BS_Fast      6.8
BS_pp        8.2
Plasma_R    11.6
Plasma_F     7.4
HbA1c       69.0
Outcomes     2.0
Name: 220, dtype: float64
Age         37.0
BS_Fast      0.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 222, dtype: float64
Age         26.0
BS_Fast     15.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 224, dtype: float64
Age         26.0
BS_Fast      0.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 226, dtype: float64
Age         31.0
BS_Fast     39.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 228, dtype: float64
Age         22.0
BS_Fast      5.8
BS_pp        6.3
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     1.0
Name: 230, dtype: float64
Age         22.0
BS_Fast     25.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 232, dtype: float64
Age         26.0
BS_Fast      6.8
BS_pp        8.2
Plasma_R    11.6
Plasma_F     7.4
HbA1c       69.0
Outcomes     2.0
Name: 235, dtype: float64
Age         27.0
BS_Fast      0.0
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 239, dtype: float64
Age         22.0
BS_Fast      6.1
BS_pp        5.7
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     2.0
Name: 242, dtype: float64
Age         29.0
BS_Fast     35.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 244, dtype: float64
Age         41.0
BS_Fast      0.0
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 246, dtype: float64
Age         34.0
BS_Fast     33.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 248, dtype: float64
Age         42.0
BS_Fast      0.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 250, dtype: float64
Age         44.0
BS_Fast      6.7
BS_pp        7.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     1.0
Name: 254, dtype: float64
Age         25.0
BS_Fast     22.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 257, dtype: float64
Age         34.0
BS_Fast     15.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 260, dtype: float64
Age         43.0
BS_Fast     18.0
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 265, dtype: float64
Age         21.0
BS_Fast      0.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 268, dtype: float64
Age         38.0
BS_Fast      6.7
BS_pp        8.7
Plasma_R    11.6
Plasma_F     7.4
HbA1c       69.0
Outcomes     1.0
Name: 270, dtype: float64
Age         40.0
BS_Fast      0.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 272, dtype: float64
Age         52.0
BS_Fast      0.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 274, dtype: float64
Age         57.0
BS_Fast      0.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 278, dtype: float64
Age         28.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     1.0
Name: 280, dtype: float64
Age         37.0
BS_Fast     15.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 282, dtype: float64
Age         51.0
BS_Fast     26.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 285, dtype: float64
Age         26.0
BS_Fast     17.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 288, dtype: float64
Age         25.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 291, dtype: float64
Age         24.0
BS_Fast      6.8
BS_pp        4.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     2.0
Name: 293, dtype: float64
Age         28.0
BS_Fast     31.0
BS_pp        5.6
Plasma_R    10.2
Plasma_F     5.4
HbA1c       32.0
Outcomes     0.0
Name: 295, dtype: float64
Age         24.0
BS_Fast     29.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 297, dtype: float64
Age         58.0
BS_Fast      0.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 299, dtype: float64
Age         47.0
BS_Fast      6.8
BS_pp        4.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     2.0
Name: 306, dtype: float64
Age         25.0
BS_Fast      5.6
BS_pp        7.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     1.0
Name: 308, dtype: float64
Age         27.0
BS_Fast      5.8
BS_pp        6.3
Plasma_R    12.6
Plasma_F     8.1
HbA1c       49.0
Outcomes     1.0
Name: 312, dtype: float64
Age         26.0
BS_Fast     22.0
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 315, dtype: float64
Age         31.0
BS_Fast     12.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 320, dtype: float64
Age         36.0
BS_Fast      6.3
BS_pp        4.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     2.0
Name: 322, dtype: float64
Age         21.0
BS_Fast     32.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 324, dtype: float64
Age         30.0
BS_Fast      6.8
BS_pp        4.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     2.0
Name: 326, dtype: float64
Age         23.0
BS_Fast      6.3
BS_pp        4.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     2.0
Name: 328, dtype: float64
Age         46.0
BS_Fast     19.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 330, dtype: float64
Age         22.0
BS_Fast     18.0
BS_pp        7.7
Plasma_R    11.0
Plasma_F     6.1
HbA1c       36.0
Outcomes     0.0
Name: 334, dtype: float64
Age         44.0
BS_Fast      5.8
BS_pp        4.2
Plasma_R    11.4
Plasma_F     8.4
HbA1c       53.0
Outcomes     2.0
Name: 337, dtype: float64
Age         41.0
BS_Fast      6.3
BS_pp        4.2
Plasma_R    12.2
Plasma_F     7.8
HbA1c       57.0
Outcomes     2.0
Name: 339, dtype: float64
Age         36.0
BS_Fast     21.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 341, dtype: float64
Age         23.0
BS_Fast      0.0
BS_pp        6.3
Plasma_R     7.9
Plasma_F     3.9
HbA1c       40.0
Outcomes     0.0
Name: 347, dtype: float64
Age         24.0
BS_Fast     12.0
BS_pp        6.8
Plasma_R    10.9
Plasma_F     4.2
HbA1c       33.0
Outcomes     0.0
Name: 353, dtype: float64
Age         49.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 355, dtype: float64
Age         44.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 357, dtype: float64
Age         29.0
BS_Fast      6.8
BS_pp        4.8
Plasma_R    13.1
Plasma_F     9.1
HbA1c       58.0
Outcomes     2.0
Name: 359, dtype: float64
Age         63.0
BS_Fast      0.0
BS_pp        5.8
Plasma_R    10.7
Plasma_F     4.8
HbA1c       28.0
Outcomes     0.0
Name: 361, dtype: float64
Age         30.0
BS_Fast     25.0
BS_pp        7.4
Plasma_R     8.7
Plasma_F     5.6
HbA1c       41.0
Outcomes     0.0
Name: 364, dtype: float64
Age         29.0
BS_Fast      6.9
BS_pp        8.4
Plasma_R    11.2
Plasma_F     7.2
HbA1c       62.0
Outcomes     2.0
Name: 366, dtype: float64
Age         25.0

In [ ]:
dataSet.head(10)

    Age  BS_Fast  BS_pp  Plasma_R  Plasma_F  HbA1c  Outcomes
0    50      6.8    8.8      11.2       7.2     62         1
2    32      6.8    8.8      11.2       7.2     62         1
4    33      6.8    8.8      11.2       7.2     62         1
6    26      5.8    4.2      11.4       8.4     53         2
8    53      6.9    8.4      11.2       7.2     62         2
9    54      6.3    4.2      12.2       7.8     57         2
11   34      5.8    4.2      11.4       8.4     53         2
13   59      6.8    8.2      11.6       7.4     69         2
14   51      6.8    8.2      11.6       7.4     69         2
15   32      5.8    4.2      11.4       8.4     53         2

In [ ]:
diabetes_Normal_count = len(dataSet.loc[dataSet['Outcomes'] == 0])
diabetes_Type1_count = len(dataSet.loc[dataSet['Outcomes'] == 1])
diabetes_Type2_count = len(dataSet.loc[dataSet['Outcomes'] == 2])

print("Normal Outcome: {0}, Type1 Outcome: {1}, Type2 Outcome: {2}".format(diabetes_Normal_count, diabetes_Type1_count, diabetes_Type2_count))

Normal Outcome: 244, Type1 Outcome: 173, Type2 Outcome: 205

In [ ]:
X = dataSet.iloc[:,:-1].values
y = dataSet.iloc[:,6].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)

### SVM

In [ ]:
from sklearn.svm import SVC
SVM_classifier = SVC(kernel = 'linear', gamma = 'auto', random_state = 0,probability=True)
SVM_classifier.fit(X_train, y_train)
SVM_y_pred = SVM_classifier.predict(X_test)
print(SVM_y_pred)
print(SVM_classifier.predict([[50,6.8,8.8,11.2,7.2,62]]))#type1
print(SVM_classifier.predict([[26,5.8,4.2,11.4,8.4,53]]))#type2
print(SVM_classifier.predict([[29,5.2,7.4,8.7,5.6,41]]))#normal

[2 0 0 1 0 1 0 0 2 1 2 0 0 2 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 2 1 1 2 2 0 0
 2 1 1 1 1 2 2 0 1 0 2 2 0 0 1 0 0 1 2 1 2 1 2 0 2 1 0 2 2 2 1 1 0 0 0 0 2
 0 0 0 2 1 2 0 1 1 1 1 0 2 1 2 2 2 2 2 0 1 1 1 2 1 2 1 0 1 1 0 1 1 0 0 0 0
 2 2 1 1 2 2 0 2 2 2 2 1 2 0 0 0 2 1 0 1 0 0 2 2 0 2 0 1 1 0 1 0 2 0 0 2 0
 0 2 0 2 0 1 2 2 1 0 0 1 0 0 0 0 1 0 1 1 2 2 2 1 2 1 2 2 1 2 2 2 1 2 0 1 1
 1 0]
[2]
[2]
[2]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_SVM = confusion_matrix(y_test, SVM_y_pred)
ac_SVM = accuracy_score(y_test, SVM_y_pred)
print("Confusion Matrix :")
print(cm_SVM)
print("SVM Train/test Split Accurary: ", ac_SVM)

pred_prob1 = SVM_classifier.predict_proba(X_test,'')

Confusion Matrix :
[[73  0  0]
 [ 0 54  0]
 [ 0  0 60]]
SVM Train/test Split Accurary:  1.0

In [ ]:
from sklearn.metrics import roc_curve

# roc curve for models
fpr1, tpr1, thresh1 = roc_curve(y_test, pred_prob1[:,1], pos_label=1)
#fpr2, tpr2, thresh2 = roc_curve(y_test, pred_prob2[:,1], pos_label=1)

# roc curve for tpr = fpr 
random_probs = [0 for i in range(len(y_test))]
p_fpr, p_tpr, _ = roc_curve(y_test, random_probs, pos_label=1)

In [ ]:
from sklearn.metrics import roc_auc_score

# auc scores
#auc_score1 = roc_auc_score(y_test, pred_prob1[:,1],multi_class='ovo')

#print(auc_score1)

AxisError: ignored

## Cross Validation on Support Vector Machine

#### 10-Fold CV

In [ ]:
##SVM_10_Fold = SVC(kernel = 'rbf', gamma = 'auto', random_state = 0)
svm_scores_10= cross_val_score(SVM_classifier,X, y,cv=10,scoring='accuracy')
print(svm_scores_10.mean())

#### 5-Fold CV

In [ ]:
##SVM_5_Fold = SVC(kernel = 'rbf', gamma = 'auto', random_state = 0)
svm_scores_5= cross_val_score(SVM_classifier,X,y,cv=5,scoring='accuracy')
print(svm_scores_5.mean())

### KNN

In [ ]:
#KNN Classifier Algorithm
from sklearn.neighbors import KNeighborsClassifier
KNNClassifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
KNNClassifier.fit(X_train, y_train)
KNN_y_pred = KNNClassifier.predict(X_test)
print(KNN_y_pred)
print(KNNClassifier.predict([[50,6.8,8.8,11.2,7.2,62]]))#type1
print(KNNClassifier.predict([[26,5.8,4.2,11.4,8.4,53]]))#type2
print(KNNClassifier.predict([[29,5.2,7.4,8.7,5.6,41]]))#normal

cm_KNNclass = confusion_matrix(y_test, KNN_y_pred)
ac_KNNclass = accuracy_score(y_test,KNN_y_pred)
print("Confusion Matrix :")
print(cm_KNNclass)
print("KNN Train/test Split Accurary: ", ac_KNNclass)

## Cross Validation on k-Nearest Neighbor

#### 10-Fold CV

In [ ]:
## KNN_10_Fold = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
scores_knn_10 = cross_val_score(KNNClassifier, X, y, cv=10, scoring='accuracy')
print(scores_knn_10.mean())

#### 5-Fold CV

In [ ]:
##KNN_5_Fold = KNeighborsClassifier(n_neighbors=5)
scores_knn_5 = cross_val_score(KNNClassifier, X, y, cv=5, scoring='accuracy')
print(scores_knn_5.mean())

### Decision Tree

In [ ]:
#Decision Tree Classifier Algorithm
from sklearn.tree import DecisionTreeClassifier
DTreeClassifier = DecisionTreeClassifier(criterion="entropy", random_state=0)
DTreeClassifier.fit(X_train, y_train)

DTree_y_pred = DTreeClassifier.predict(X_test)

cm_DTree = confusion_matrix(y_test, DTree_y_pred)
ac_DTree = accuracy_score(y_test, DTree_y_pred)
print("Decision Tree Train/test Split Confusion Matrix :")
print(cm_DTree)
print("Decision Tree Train/test Split Accurary: ", ac_DTree)

## Cross Validation on Decision Tree

#### 10-Fold CV

In [ ]:
##DTreeClassifier_10_Fold = DecisionTreeClassifier(criterion="entropy", random_state=0)
scores_dt_10 = cross_val_score(DTreeClassifier, X, y, cv=10, scoring='accuracy')
print(scores_dt_10.mean())

#### 5-Fold CV

In [ ]:
##DTreeClassifier_5_Fold = DecisionTreeClassifier(criterion="entropy", random_state=0)
scores_dt_5 = cross_val_score(DTreeClassifier, X, y, cv=5, scoring='accuracy')
print(scores_dt_5.mean())

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
LogisticClassifier = LogisticRegression(random_state = 0)
LogisticClassifier.fit(X_train, y_train)

log_y_pred = LogisticClassifier.predict(X_test)

cm_log_reg = confusion_matrix(y_test, log_y_pred)
ac_log_reg = accuracy_score(y_test,log_y_pred)
print("Logistic Regression Train/test Split Confusion Matrix :")
print(cm_log_reg)
print("Logistic Regression Train/test Split Accurary: ", ac_log_reg)

## Cross Validation on Logistics Regression

#### 10-Fold CV

In [ ]:
LogisticClassifier_10_Fold = LogisticRegression(random_state = 0)
scores_log_10 = cross_val_score(LogisticClassifier_10_Fold, X_train, y_train, cv=10, scoring='accuracy')
print(scores_log_10.mean())

#### 5-Fold CV

In [ ]:
LogisticClassifier_5_Fold = LogisticRegression(random_state = 0)
scores_log_5 = cross_val_score(LogisticClassifier_5_Fold, X_train, y_train, cv=5, scoring='accuracy')
print(scores_log_5.mean())

### Naive-Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
NBclassifier = GaussianNB()
NBclassifier.fit(X_train, y_train)

NB_y_pred = NBclassifier.predict(X_test)

cm_NBclass = confusion_matrix(y_test, NB_y_pred)
ac_NBclass = accuracy_score(y_test,NB_y_pred)
print("Naive-Bayes Train/Test Split Accuracy: ", ac_NBclass)
print("confusion matrix of Naive Bayes:",cm_NBclass)

## Cross Validation on Naive Bayes

#### 10-Fold CV

In [ ]:
#NBclassifier_10_Fold = GaussianNB()
scores_nb_10 = cross_val_score(NBclassifier, X, y, cv=10, scoring='accuracy')
print(scores_nb_10.mean())

#### 5-Fold CV

In [ ]:
#NBclassifier_10_Fold = GaussianNB()
scores_nb_5 = cross_val_score(NBclassifier, X, y, cv=5, scoring='accuracy')
print(scores_nb_5.mean())

### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
randomForestClassifier=RandomForestClassifier(n_estimators=100)
randomForestClassifier.fit(X_train,y_train)

randomForestClassifier.score(X_test,y_test)
rand_y_pred=randomForestClassifier.predict(X_test)

cm_randomForest= confusion_matrix(y_test,rand_y_pred)
ac_randomFores= accuracy_score(y_test,rand_y_pred)
print("Random Forest Classifier Accuracy:",ac_randomFores)
print("Random Forest Classifier Confusion Matrix",cm_randomForest)

## Cross Validation on Random Forest

#### 10-Fold CV

In [ ]:
##RForestClassifier_10_Fold=RandomForestClassifier(n_estimators=100)
scores_rf_10 = cross_val_score(randomForestClassifier, X, y, cv=10, scoring='accuracy')
print(scores_rf_10.mean())

#### 5-Fold CV

In [ ]:
##RForestClassifier_5_Fold=RandomForestClassifier(n_estimators=100)
scores_rf_5 = cross_val_score(randomForestClassifier, X, y, cv=5, scoring='accuracy')
print(scores_rf_5.mean())